### ISSUE TITLE
State Management Agnostic library but dependency on React

### ISSUE THREAD

**Issue by tenhsor1** [onurkerimov/xoid#10]
First of all, great work with the API! I'm exploring options for implementing an state management library in a low-code no-code editor we are working on, and I have so far xoid as the first option, as it checks a lot of the requirements we have.

One of those requirements though, is that it will be reused across multiple frontend clients, built using any number of frameworks. Seems like the library is supposed to be agnostic, but I still see that there's a dependency on `react` and `react-dom` in the package.json, why is this needed? Am I missing something? 
If I'm just planning on using the `core`, would this package still require `react`? Thanks in advance.

**Comment by onurkerimov** [comment]
Hi @tenhsor1 ! Thank you for the kind words. Good luck on the product your're working on. I'm very happy to hear that you considered xoid as the first option. 

I think you're talking about the project root package.json. The core package (that resides in `packages/xoid` in this repo) has no dependency to `react` or `react-dom`, or any other external dependency.  You can browse the shape it's shipped from npm here: https://unpkg.com/browse/xoid@1.0.0-beta.4/package.json

I hope this answers your question!
