### ISSUE TITLE
Failed to infer Atom of create() upon DTS generation via tsc/tsup

### ISSUE THREAD

**Issue by thihathit** [onurkerimov/xoid#4]
First of all, thank you for the library with it's simple API, super awesome work!

![image](https://user-images.githubusercontent.com/30023628/196614795-4f6fac93-9ee0-4929-8307-64bc3762f25a.png)

### How did this happen?

It happens when the consuming project uses `pnpm` & tries to generate `.d.ts` files via either `tsup`(uses `tsc` under the hood) or `tsc`.

### Example

```ts
import { create } from 'xoid/esm'

const atom = create({ one: true })

const atom2 = create({ two: true })
```

### Workaround

The workaround is to define type, at least once per file where `create` is used.

```ts
import { create, Atom } from 'xoid/esm'

const atom: Atom<{ one: boolean }> = create({ one: true })

const atom2 = create({ two: true })
```

IMO, this only happens on libraries with some sort of shared module structure, `xoid/etc...`. So I'm not sure on which one's end, `tsc`, `pnpm` or `xoid`. Another similar issue is with [`nuxt`'s](https://github.com/egoist/tsup/issues/624) sub-modules.

Might also related to this `tsc` issue: [#42873](https://github.com/microsoft/TypeScript/issues/42873)

**Comment by onurkerimov** [comment]
Hi @thihathit, thank you for the kind words, and thank you for reporting!
Does the problem disappear if xoid is imported from `'xoid'` and not `'xoid/esm'`?
In the first major version, I'm planning to change imports such that:
```
"main": "index.js",
"module": "index.esm.js"
```
I believe it will fix the same problem for some environments.

**Comment by thihathit** [comment]
Sadly `xoid` is also affected

**Comment by onurkerimov** [comment]
The 1.0.0-beta.0 release addresses this issue. There's only one `index.d.ts` file and therefore the same problem shouldn't occur anymore, so I'm closing this issue.

**Comment by thihathit** [comment]
yes, it's working on beta. thank you.
