### ISSUE TITLE
Simple type definition?

### ISSUE THREAD

**Issue by jgentes** [onurkerimov/xoid#6]
Great docs, the library looks great!

I'm starting with something simple, and was hoping to provide a simple types definition, such as:
```ts
const table = create({legs: 4, painted: false}: {legs: number, painted: boolean})
```

But it seems that's not possible. Is there another simple syntax, or would I need to follow what you have in the examples?

**Comment by feskovio** [comment]
I believe, you could use a generic type modifier as follows:
`const table = create<{legs: number, painted: boolean}>({legs: 4, painted: false});`

Alternatively, if you have an interface or a type defined somewhere in your code, just use it like this:
`const table = create<InterfaceName>({legs: 4, painted: false});`

**Comment by jgentes** [comment]
Thank you!
